# Generated by Django 4.2 on 2024-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=128)),
                ('user_input', models.CharField(max_length=128)),
                ('bot_response', models.CharField(max_length=128)),
                ('required_words', models.CharField(max_length=128)),
            ],
        ),
    ]
