# Generated by Django 5.0.2 on 2024-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodel',
            name='bot_response',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='required_words',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='response_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='user_input',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
