# Generated by Django 5.0.2 on 2024-02-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_alter_trainmodel_bot_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainModel',
            new_name='BotResponse',
        ),
    ]
