# Generated by Django 5.0.2 on 2024-03-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0004_dashboardiamge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardIamge',
            new_name='DashboardImage',
        ),
    ]
